### ISSUE TITLE
[Question] !ENABLE_ICACHE_PACKET_BREAKING && !PERFECT_BP

### ISSUE THREAD

**Issue by hlitz** [hpsresearchgroup/scarab#111]
(at least in trace mode) if I disable ENABLE_ICACHE_PACKET_BREAKING and also disable the perfect branch predictor, running scarab fails with ic->next_fetch_addr == op->inst_info->addr

Looking into packet_build.c I see:

    if(ENABLE_ICACHE_PACKET_BREAKING) {
      // control flow instruction
      if(op->table_info->cf_type)
        return PB_BREAK_AFTER;
    }

If I understand correctly if ENABLE_ICACHE_PACKET_BREAKING is enabled, scarab breaks after every CF instruction (no modern architecture breaks after correctly predicted non-taken branches so I want to disable it). 

Now, with ENABLE_ICACHE_PACKET_BREAKING disabled, when the first branch is mispredicted the instruction after the branch is incorrect as, I assume, the icache_stage/packet_build reads an instruction from the trace that does not match the predicted instructions PC. The problem is that packet_build happens before branch prediction and so during packet build, we do not know whether we are staying on the ON_PATH or going OFF_PATH. It seems that the next instruction after the branch is determined before the branch is predicted. If we knew that the CF is going to be mispredicted we could break only in this case but currently, it breaks after each CF even after those that are correctly predicted.

I believe this problem should also cause issues for exec_driven mode as the PIN-frontend can only be re-steered if a branch misprediction is detected.

Let me know if I am missing sth and if you have an idea to solve this problem (not breaking after each CF without perfect branch predictor)

**Comment by hlitz** [comment]
@siavashzk The problem is that ENABLE_ICACHE_PACKET_BREAKING causes breaks on multiple conditions. The mentioned CFS_PER_CYCLE break is not the problem but the same ENABLE_ICACHE_PACKET_BREAKING is used a couple lines below again to also break on _all_ CF instructions. BTW, this has a huge impact on IPC and I think it is unrealistic for most architectures.

**Comment by siavashzk** [comment]
Hi Hiener,

The packet_build code is confusing, but it turns out that @spruett had looked into this before and has a detailed response on how it works in this [past issue](https://github.com/hpsresearchgroup/scarab/issues/42). The summary is that break_fetch and packet_break serve different purposes, and on every CF instructions, only packet_breat is set, not break_fetch. So, based on our current understanding and what we observe in our debug runs, we are not breaking after every branch. Are you seeing different behavior?

Regarding the bug with the !ENABLE_ICACHE_PACKET_BREAKING && !PERFECT_BP combo, I think your fix looks good, and just did it myself.

**Comment by spruett** [comment]
Siavash and I realized there is one other point on this matter worth mentioning. It is possible you are seeing IPC differences because by disabling `ENABLE_ICACHE_PACKET_BREAKING` you may be changing the icache access pattern. Please see below.

Again, the way the code is written is very confusing here, so I am going to apologize in advance for the confusing variable names. 

There are two variables of interest here: `break_fetch` and `packet_break`. 

If `break_fetch` is set, this essentially ends the cycle at the current instruction. In other words, `icache_issue_ops` will continue to issue ops in the SAME cycle UNTIL `break_fetch` is set, which will cause the while loop in `update_icache_stage` to end.

`packet_break` serves a completely different purpose. Each time `packet_break` is set, this will cause another i-cache access to be modeled (see `update_icache_stage` function). This is what the knob `ENABLE_ICACHE_PACKET_BREAKING` is enabling/disabling. When `ENABLE_ICACHE_PACKET_BREAKING=true`, there will be an i-cache access when: 
1. Any branch is seen (see line `packet_build.c:247`) or
2. When a cache line boundary is reached (see line `packet_build:226`)

When `ENABLE_ICACHE_PACKET_BREAKING=false`, then the number of icache accesses may go down, because the `icache_issue_ops` function is not properly returning to `update_icache_stage` to model the next cache access. In the worst case, if you fetch multiple taken branches in one cycle, you could end up skipping an access to an i-cache line all together. 

One last thing to note: right now `packet_break` is set after any branch (`packet_build.c:247`). It may be more accurate to change this to only be set after TAKEN branches. This is likely increasing accesses to the same cache line, and thereby increase the `ICACHE_HIT` stat, which will affect the perceived cache hit rate and power modeling.
