### ISSUE TITLE
[BUG] Running SPEC2006 Checkpoints with PIN tool 

### ISSUE THREAD

**Issue by sanjana879** [hpsresearchgroup/scarab#117]
**Describe the bug**
When running a generated checkpoint from SPEC 2006, Scarab hangs because of an error with Pin's parent and child injection modes.
```
Writing data to all regions ...
Updating region protection fields ...
Loading the floating-point state ...
Loading the architectural registers ...
Detaching ptrace from the child process ...
E: Attach to pid 20057 failed.
E:   The Operating System configuration prevents Pin from using the default (parent) injection mode.
E:   To resolve this, either execute the following (as root):
E:   $ echo 0 > /proc/sys/kernel/yama/ptrace_scope
E:   Or use the "-injection child" option.
E:   For more information, regarding child injection, see Injection section in the Pin User Manual.
E: 
```

I can't execute the echo command because I don't have root access on the lab machines and the "-injection child" option doesn't work and just outputs this error instead:

`E: unknown option "child"`

**To Reproduce**
1. Generate SPEC 2006 Checkpoints 
2. Run command: `python3 bin/scarab_launch.py --params src/PARAMS.kaby_lake --simdir test_run --checkpoint <PATH TO SPEC CHECKPOINTS>/bzip2_06/test/bzip2_06_test0_checkpoint3_0.28053003572169843_6900001396 --scarab_args='--inst_limit 30000000'`
3. See error on Terminal

**Expected behavior**
Scarab should run and simulate that checkpoint 

**Desktop (please complete the following information):**
 - OS: Ubuntu (jalad lab machine)
 - Browser: Chrome
 - Version: Ubuntu 18.04, Chrome 96

**Comment by siavashzk** [comment]
The problem was that the main checkpoint loader spawned the pintool and the loaded checkpoint as two sibling processes. If Yama's ptrace scope is restricted (ptrace_scope >= 1), the kernel would not allow the PIN process to be attached. The solution (now merged in PR #120 ) maintains a parent/child relationship between the pintool and the loaded process, which is acceptable even if Yama's ptrace_scope is configured as 1.
