### ISSUE TITLE
[Question] BTB updating on not taken branch

### ISSUE THREAD

**Issue by petervbraun** [hpsresearchgroup/scarab#95]
An entry is added to the BTB on a not taken branch. Later, when a branch is taken the BTB entry is not updated. Is there a reason for this behavior or is this a bug?

You can see this behavior by stepping through the code following any branch.
Looking at the most recent commit in the master branch:
Updating the BTB only happens in bp.c:610 when the op is tagged as a BTB miss.
However, an op is tagged as a BTB miss at bp.c:347 in bp_target_known_op() if the BTB does not have an entry for the branch, regardless of whether the branch was taken/not taken or predicted correctly/incorrectly.

This causes many BTB misses to be incorrectly labeled as misfetches. For example, a direct conditional branch should never miss in the BTB since only the target on the taken path should be stored.

I am running a workload on the memtrace branch but the code in question is identical on the master.
Thanks!

**Comment by hlitz** [comment]
Just to clarify, in fact, we have two questions.
1. Why are we inserting in the BTB on a non-taken branch?
2. Why are we inserting the nextPC (fall through path!) and not the branch target?

**Comment by spruett** [comment]
To answer this, lets go over how the BTB in Scarab works. 

The BTB in Scarab really has two responsibilities: 1) Let the icache_stage know that the current instruction is a branch and 2) supply the target of the branch, which is only needed in the case of taken branches. See my response [here](https://github.com/hpsresearchgroup/scarab/issues/93) for a better description of these two responsibilities. 

On a BTB miss, scarab stalls the icache_stage and waits until the branch target is known (either by decode for direct branches or execute for indirect branches)<sup>1</sup>. Once a direct branch makes it to decode, the decoder will discover that it is in fact a branch and install an entry in the BTB so that it can correctly identify that instruction in the future. This happens regardless of whether the branch is taken or not taken. Additionally, the target (PC + offset) is decoded and installed into the BTB as well (again, even if the branch is not-taken). This will warm up the BTB faster than if we had waited for a taken branch<sup>2</sup>. 

**A few notes:**
[1] On a BTB miss, a real machine has no knowledge that a branch occurred, since it has not reached decode yet. Therefore, on a real machine the instruction will be effectively treated like a not-taken branch. This is technically an inaccuracy in Scarab. The quickest fix here would be to only stall if there was a BTB miss AND the branch was taken; however, an even more accurate solution should also be fairly straight forward. If you do find/fix any bugs or develop any features that you think would help out the community, please don't hesitate to [make a pull request](https://github.com/hpsresearchgroup/scarab/pulls).
[2] Some implementations may choose not to install BTB entries until the first taken instance of the branch is seen. This may improve effective BTB capacity if there are many never-taken branches. It would be perfectly acceptable to modify Scarab to operate like this if you so choose. 

So, on to your questions:
**1. Why are we inserting in the BTB on a non-taken branch?**
Because the target (pc + offset) can be computed easily even when the branch is not taken. By training the BTB on all branches, we can warm up faster. 

**2. Why are we (in case of not-taken) inserting the nextPC (fall through path!) and not the branch target?**
Scarab (should be) always inserting the target of the branch (regardless of the branch direction). Please see `bp_targ_mech.c:bp_btb_gen_update`. Inside that function you will find this line:
```
...
*btb_line = op->oracle_info.target;
...
```

`op->oracle_info.target` *should* always be set to the branch target. This variable is set by the Scarab frontend (either PIN or TRACE). You mentioned you were working on another branch (memtrace). Does the branch have a new or modified frontend? If so can you repeat your experiment on the main scarab branch and see if you are having the same issue?

Let me know how it goes.

**Comment by petervbraun** [comment]
Thanks for the detailed clarification! I found a bug in our new frontend where `op->oracle_info->target` was not set up correctly.
